git:
  filters:
  - filter_type: file
    source_file: src/i18n/jmxweb_i18n.properties
    file_format: UNICODEPROPERTIES
    translation_files_expression: 'src/i18n/jmxweb_i18n_<lang>.properties'
    source_language: en
